/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePedidoDto
 */
export interface CreatePedidoDto {
    /**
     * 
     * @type {number}
     * @memberof CreatePedidoDto
     */
    qtInteira: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePedidoDto
     */
    qtMeia: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePedidoDto
     */
    valorTotal: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreatePedidoDto
     */
    ingressoIds: Array<number>;
}

/**
 * Check if a given object implements the CreatePedidoDto interface.
 */
export function instanceOfCreatePedidoDto(value: object): value is CreatePedidoDto {
    if (!('qtInteira' in value) || value['qtInteira'] === undefined) return false;
    if (!('qtMeia' in value) || value['qtMeia'] === undefined) return false;
    if (!('valorTotal' in value) || value['valorTotal'] === undefined) return false;
    if (!('ingressoIds' in value) || value['ingressoIds'] === undefined) return false;
    return true;
}

export function CreatePedidoDtoFromJSON(json: any): CreatePedidoDto {
    return CreatePedidoDtoFromJSONTyped(json, false);
}

export function CreatePedidoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePedidoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'qtInteira': json['qtInteira'],
        'qtMeia': json['qtMeia'],
        'valorTotal': json['valorTotal'],
        'ingressoIds': json['ingressoIds'],
    };
}

export function CreatePedidoDtoToJSON(json: any): CreatePedidoDto {
    return CreatePedidoDtoToJSONTyped(json, false);
}

export function CreatePedidoDtoToJSONTyped(value?: CreatePedidoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qtInteira': value['qtInteira'],
        'qtMeia': value['qtMeia'],
        'valorTotal': value['valorTotal'],
        'ingressoIds': value['ingressoIds'],
    };
}

