/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSalaDtoPoutronasInner
 */
export interface CreateSalaDtoPoutronasInner {
}

/**
 * Check if a given object implements the CreateSalaDtoPoutronasInner interface.
 */
export function instanceOfCreateSalaDtoPoutronasInner(value: object): value is CreateSalaDtoPoutronasInner {
    return true;
}

export function CreateSalaDtoPoutronasInnerFromJSON(json: any): CreateSalaDtoPoutronasInner {
    return CreateSalaDtoPoutronasInnerFromJSONTyped(json, false);
}

export function CreateSalaDtoPoutronasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSalaDtoPoutronasInner {
    return json;
}

export function CreateSalaDtoPoutronasInnerToJSON(json: any): CreateSalaDtoPoutronasInner {
    return CreateSalaDtoPoutronasInnerToJSONTyped(json, false);
}

export function CreateSalaDtoPoutronasInnerToJSONTyped(value?: CreateSalaDtoPoutronasInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

