/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLancheComboDto
 */
export interface CreateLancheComboDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLancheComboDto
     */
    nome: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLancheComboDto
     */
    descricao: string;
    /**
     * 
     * @type {number}
     * @memberof CreateLancheComboDto
     */
    valorUnitario: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLancheComboDto
     */
    qtUnidade: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLancheComboDto
     */
    subtotal: number;
    /**
     * 
     * @type {number}
     * @memberof CreateLancheComboDto
     */
    pedidoId: number;
}

/**
 * Check if a given object implements the CreateLancheComboDto interface.
 */
export function instanceOfCreateLancheComboDto(value: object): value is CreateLancheComboDto {
    if (!('nome' in value) || value['nome'] === undefined) return false;
    if (!('descricao' in value) || value['descricao'] === undefined) return false;
    if (!('valorUnitario' in value) || value['valorUnitario'] === undefined) return false;
    if (!('qtUnidade' in value) || value['qtUnidade'] === undefined) return false;
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    if (!('pedidoId' in value) || value['pedidoId'] === undefined) return false;
    return true;
}

export function CreateLancheComboDtoFromJSON(json: any): CreateLancheComboDto {
    return CreateLancheComboDtoFromJSONTyped(json, false);
}

export function CreateLancheComboDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLancheComboDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nome': json['nome'],
        'descricao': json['descricao'],
        'valorUnitario': json['valorUnitario'],
        'qtUnidade': json['qtUnidade'],
        'subtotal': json['subtotal'],
        'pedidoId': json['pedidoId'],
    };
}

export function CreateLancheComboDtoToJSON(json: any): CreateLancheComboDto {
    return CreateLancheComboDtoToJSONTyped(json, false);
}

export function CreateLancheComboDtoToJSONTyped(value?: CreateLancheComboDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nome': value['nome'],
        'descricao': value['descricao'],
        'valorUnitario': value['valorUnitario'],
        'qtUnidade': value['qtUnidade'],
        'subtotal': value['subtotal'],
        'pedidoId': value['pedidoId'],
    };
}

