/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSalaDtoPoutronasInner } from './CreateSalaDtoPoutronasInner';
import {
    CreateSalaDtoPoutronasInnerFromJSON,
    CreateSalaDtoPoutronasInnerFromJSONTyped,
    CreateSalaDtoPoutronasInnerToJSON,
    CreateSalaDtoPoutronasInnerToJSONTyped,
} from './CreateSalaDtoPoutronasInner';

/**
 * 
 * @export
 * @interface CreateSalaDto
 */
export interface CreateSalaDto {
    /**
     * 
     * @type {number}
     * @memberof CreateSalaDto
     */
    numero: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSalaDto
     */
    capacidade: number;
    /**
     * Poltronas da sala (array de inteiros ou matriz)
     * @type {Array<CreateSalaDtoPoutronasInner>}
     * @memberof CreateSalaDto
     */
    poutronas: Array<CreateSalaDtoPoutronasInner>;
    /**
     * 
     * @type {number}
     * @memberof CreateSalaDto
     */
    cinemaId: number;
}

/**
 * Check if a given object implements the CreateSalaDto interface.
 */
export function instanceOfCreateSalaDto(value: object): value is CreateSalaDto {
    if (!('numero' in value) || value['numero'] === undefined) return false;
    if (!('capacidade' in value) || value['capacidade'] === undefined) return false;
    if (!('poutronas' in value) || value['poutronas'] === undefined) return false;
    if (!('cinemaId' in value) || value['cinemaId'] === undefined) return false;
    return true;
}

export function CreateSalaDtoFromJSON(json: any): CreateSalaDto {
    return CreateSalaDtoFromJSONTyped(json, false);
}

export function CreateSalaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSalaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'numero': json['numero'],
        'capacidade': json['capacidade'],
        'poutronas': ((json['poutronas'] as Array<any>).map(CreateSalaDtoPoutronasInnerFromJSON)),
        'cinemaId': json['cinemaId'],
    };
}

export function CreateSalaDtoToJSON(json: any): CreateSalaDto {
    return CreateSalaDtoToJSONTyped(json, false);
}

export function CreateSalaDtoToJSONTyped(value?: CreateSalaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numero': value['numero'],
        'capacidade': value['capacidade'],
        'poutronas': ((value['poutronas'] as Array<any>).map(CreateSalaDtoPoutronasInnerToJSON)),
        'cinemaId': value['cinemaId'],
    };
}

