/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSessaoDto
 */
export interface CreateSessaoDto {
    /**
     * 
     * @type {Date}
     * @memberof CreateSessaoDto
     */
    horarioExibicao: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateSessaoDto
     */
    filmeId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSessaoDto
     */
    salaId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateSessaoDto
     */
    cinemaId: number;
}

/**
 * Check if a given object implements the CreateSessaoDto interface.
 */
export function instanceOfCreateSessaoDto(value: object): value is CreateSessaoDto {
    if (!('horarioExibicao' in value) || value['horarioExibicao'] === undefined) return false;
    if (!('filmeId' in value) || value['filmeId'] === undefined) return false;
    if (!('salaId' in value) || value['salaId'] === undefined) return false;
    if (!('cinemaId' in value) || value['cinemaId'] === undefined) return false;
    return true;
}

export function CreateSessaoDtoFromJSON(json: any): CreateSessaoDto {
    return CreateSessaoDtoFromJSONTyped(json, false);
}

export function CreateSessaoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessaoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'horarioExibicao': (new Date(json['horarioExibicao'])),
        'filmeId': json['filmeId'],
        'salaId': json['salaId'],
        'cinemaId': json['cinemaId'],
    };
}

export function CreateSessaoDtoToJSON(json: any): CreateSessaoDto {
    return CreateSessaoDtoToJSONTyped(json, false);
}

export function CreateSessaoDtoToJSONTyped(value?: CreateSessaoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'horarioExibicao': ((value['horarioExibicao']).toISOString()),
        'filmeId': value['filmeId'],
        'salaId': value['salaId'],
        'cinemaId': value['cinemaId'],
    };
}

