/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCinemaDto
 */
export interface CreateCinemaDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCinemaDto
     */
    nome: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCinemaDto
     */
    endereco: string;
}

/**
 * Check if a given object implements the CreateCinemaDto interface.
 */
export function instanceOfCreateCinemaDto(value: object): value is CreateCinemaDto {
    if (!('nome' in value) || value['nome'] === undefined) return false;
    if (!('endereco' in value) || value['endereco'] === undefined) return false;
    return true;
}

export function CreateCinemaDtoFromJSON(json: any): CreateCinemaDto {
    return CreateCinemaDtoFromJSONTyped(json, false);
}

export function CreateCinemaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCinemaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nome': json['nome'],
        'endereco': json['endereco'],
    };
}

export function CreateCinemaDtoToJSON(json: any): CreateCinemaDto {
    return CreateCinemaDtoToJSONTyped(json, false);
}

export function CreateCinemaDtoToJSONTyped(value?: CreateCinemaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nome': value['nome'],
        'endereco': value['endereco'],
    };
}

