/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFilmeDto
 */
export interface CreateFilmeDto {
    /**
     * 
     * @type {string}
     * @memberof CreateFilmeDto
     */
    titulo: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFilmeDto
     */
    sinopse: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFilmeDto
     */
    classificacao: string;
    /**
     * 
     * @type {number}
     * @memberof CreateFilmeDto
     */
    duracao: number;
    /**
     * 
     * @type {string}
     * @memberof CreateFilmeDto
     */
    elenco: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFilmeDto
     */
    genero: CreateFilmeDtoGeneroEnum;
    /**
     * 
     * @type {Date}
     * @memberof CreateFilmeDto
     */
    dataIniciaExibicao: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateFilmeDto
     */
    dataFinalExibicao: Date;
}


/**
 * @export
 */
export const CreateFilmeDtoGeneroEnum = {
    Acao: 'ACAO',
    Aventura: 'AVENTURA',
    Comedia: 'COMEDIA',
    Drama: 'DRAMA',
    Fantasia: 'FANTASIA',
    FiccaoCientifica: 'FICCAO_CIENTIFICA',
    Terror: 'TERROR',
    Romance: 'ROMANCE',
    Animacao: 'ANIMACAO',
    Documentario: 'DOCUMENTARIO',
    Suspense: 'SUSPENSE',
    Musical: 'MUSICAL',
    Outro: 'OUTRO'
} as const;
export type CreateFilmeDtoGeneroEnum = typeof CreateFilmeDtoGeneroEnum[keyof typeof CreateFilmeDtoGeneroEnum];


/**
 * Check if a given object implements the CreateFilmeDto interface.
 */
export function instanceOfCreateFilmeDto(value: object): value is CreateFilmeDto {
    if (!('titulo' in value) || value['titulo'] === undefined) return false;
    if (!('sinopse' in value) || value['sinopse'] === undefined) return false;
    if (!('classificacao' in value) || value['classificacao'] === undefined) return false;
    if (!('duracao' in value) || value['duracao'] === undefined) return false;
    if (!('elenco' in value) || value['elenco'] === undefined) return false;
    if (!('genero' in value) || value['genero'] === undefined) return false;
    if (!('dataIniciaExibicao' in value) || value['dataIniciaExibicao'] === undefined) return false;
    if (!('dataFinalExibicao' in value) || value['dataFinalExibicao'] === undefined) return false;
    return true;
}

export function CreateFilmeDtoFromJSON(json: any): CreateFilmeDto {
    return CreateFilmeDtoFromJSONTyped(json, false);
}

export function CreateFilmeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFilmeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'titulo': json['titulo'],
        'sinopse': json['sinopse'],
        'classificacao': json['classificacao'],
        'duracao': json['duracao'],
        'elenco': json['elenco'],
        'genero': json['genero'],
        'dataIniciaExibicao': (new Date(json['dataIniciaExibicao'])),
        'dataFinalExibicao': (new Date(json['dataFinalExibicao'])),
    };
}

export function CreateFilmeDtoToJSON(json: any): CreateFilmeDto {
    return CreateFilmeDtoToJSONTyped(json, false);
}

export function CreateFilmeDtoToJSONTyped(value?: CreateFilmeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'titulo': value['titulo'],
        'sinopse': value['sinopse'],
        'classificacao': value['classificacao'],
        'duracao': value['duracao'],
        'elenco': value['elenco'],
        'genero': value['genero'],
        'dataIniciaExibicao': ((value['dataIniciaExibicao']).toISOString()),
        'dataFinalExibicao': ((value['dataFinalExibicao']).toISOString()),
    };
}

