/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateIngressoDto
 */
export interface CreateIngressoDto {
    /**
     * 
     * @type {number}
     * @memberof CreateIngressoDto
     */
    valorInteira: number;
    /**
     * 
     * @type {number}
     * @memberof CreateIngressoDto
     */
    valorMeia: number;
    /**
     * 
     * @type {number}
     * @memberof CreateIngressoDto
     */
    sessaoId: number;
}

/**
 * Check if a given object implements the CreateIngressoDto interface.
 */
export function instanceOfCreateIngressoDto(value: object): value is CreateIngressoDto {
    if (!('valorInteira' in value) || value['valorInteira'] === undefined) return false;
    if (!('valorMeia' in value) || value['valorMeia'] === undefined) return false;
    if (!('sessaoId' in value) || value['sessaoId'] === undefined) return false;
    return true;
}

export function CreateIngressoDtoFromJSON(json: any): CreateIngressoDto {
    return CreateIngressoDtoFromJSONTyped(json, false);
}

export function CreateIngressoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIngressoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'valorInteira': json['valorInteira'],
        'valorMeia': json['valorMeia'],
        'sessaoId': json['sessaoId'],
    };
}

export function CreateIngressoDtoToJSON(json: any): CreateIngressoDto {
    return CreateIngressoDtoToJSONTyped(json, false);
}

export function CreateIngressoDtoToJSONTyped(value?: CreateIngressoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valorInteira': value['valorInteira'],
        'valorMeia': value['valorMeia'],
        'sessaoId': value['sessaoId'],
    };
}

