/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalaControllerReservarPoutronaRequest
 */
export interface SalaControllerReservarPoutronaRequest {
    /**
     * 
     * @type {number}
     * @memberof SalaControllerReservarPoutronaRequest
     */
    fila: number;
    /**
     * 
     * @type {number}
     * @memberof SalaControllerReservarPoutronaRequest
     */
    num: number;
}

/**
 * Check if a given object implements the SalaControllerReservarPoutronaRequest interface.
 */
export function instanceOfSalaControllerReservarPoutronaRequest(value: object): value is SalaControllerReservarPoutronaRequest {
    if (!('fila' in value) || value['fila'] === undefined) return false;
    if (!('num' in value) || value['num'] === undefined) return false;
    return true;
}

export function SalaControllerReservarPoutronaRequestFromJSON(json: any): SalaControllerReservarPoutronaRequest {
    return SalaControllerReservarPoutronaRequestFromJSONTyped(json, false);
}

export function SalaControllerReservarPoutronaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalaControllerReservarPoutronaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fila': json['fila'],
        'num': json['num'],
    };
}

export function SalaControllerReservarPoutronaRequestToJSON(json: any): SalaControllerReservarPoutronaRequest {
    return SalaControllerReservarPoutronaRequestToJSONTyped(json, false);
}

export function SalaControllerReservarPoutronaRequestToJSONTyped(value?: SalaControllerReservarPoutronaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fila': value['fila'],
        'num': value['num'],
    };
}

