/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCinemaDto
 */
export interface UpdateCinemaDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCinemaDto
     */
    nome?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCinemaDto
     */
    endereco?: string;
}

/**
 * Check if a given object implements the UpdateCinemaDto interface.
 */
export function instanceOfUpdateCinemaDto(value: object): value is UpdateCinemaDto {
    return true;
}

export function UpdateCinemaDtoFromJSON(json: any): UpdateCinemaDto {
    return UpdateCinemaDtoFromJSONTyped(json, false);
}

export function UpdateCinemaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCinemaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nome': json['nome'] == null ? undefined : json['nome'],
        'endereco': json['endereco'] == null ? undefined : json['endereco'],
    };
}

export function UpdateCinemaDtoToJSON(json: any): UpdateCinemaDto {
    return UpdateCinemaDtoToJSONTyped(json, false);
}

export function UpdateCinemaDtoToJSONTyped(value?: UpdateCinemaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nome': value['nome'],
        'endereco': value['endereco'],
    };
}

