/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePedidoDto
 */
export interface UpdatePedidoDto {
    /**
     * 
     * @type {number}
     * @memberof UpdatePedidoDto
     */
    qtInteira?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdatePedidoDto
     */
    qtMeia?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdatePedidoDto
     */
    valorTotal?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdatePedidoDto
     */
    ingressoIds?: Array<number>;
}

/**
 * Check if a given object implements the UpdatePedidoDto interface.
 */
export function instanceOfUpdatePedidoDto(value: object): value is UpdatePedidoDto {
    return true;
}

export function UpdatePedidoDtoFromJSON(json: any): UpdatePedidoDto {
    return UpdatePedidoDtoFromJSONTyped(json, false);
}

export function UpdatePedidoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePedidoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'qtInteira': json['qtInteira'] == null ? undefined : json['qtInteira'],
        'qtMeia': json['qtMeia'] == null ? undefined : json['qtMeia'],
        'valorTotal': json['valorTotal'] == null ? undefined : json['valorTotal'],
        'ingressoIds': json['ingressoIds'] == null ? undefined : json['ingressoIds'],
    };
}

export function UpdatePedidoDtoToJSON(json: any): UpdatePedidoDto {
    return UpdatePedidoDtoToJSONTyped(json, false);
}

export function UpdatePedidoDtoToJSONTyped(value?: UpdatePedidoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qtInteira': value['qtInteira'],
        'qtMeia': value['qtMeia'],
        'valorTotal': value['valorTotal'],
        'ingressoIds': value['ingressoIds'],
    };
}

