/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSalaDtoPoutronasInner } from './CreateSalaDtoPoutronasInner';
import {
    CreateSalaDtoPoutronasInnerFromJSON,
    CreateSalaDtoPoutronasInnerFromJSONTyped,
    CreateSalaDtoPoutronasInnerToJSON,
    CreateSalaDtoPoutronasInnerToJSONTyped,
} from './CreateSalaDtoPoutronasInner';

/**
 * 
 * @export
 * @interface UpdateSalaDto
 */
export interface UpdateSalaDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateSalaDto
     */
    numero?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSalaDto
     */
    capacidade?: number;
    /**
     * Poltronas da sala (array de inteiros ou matriz)
     * @type {Array<CreateSalaDtoPoutronasInner>}
     * @memberof UpdateSalaDto
     */
    poutronas?: Array<CreateSalaDtoPoutronasInner>;
    /**
     * 
     * @type {number}
     * @memberof UpdateSalaDto
     */
    cinemaId?: number;
}

/**
 * Check if a given object implements the UpdateSalaDto interface.
 */
export function instanceOfUpdateSalaDto(value: object): value is UpdateSalaDto {
    return true;
}

export function UpdateSalaDtoFromJSON(json: any): UpdateSalaDto {
    return UpdateSalaDtoFromJSONTyped(json, false);
}

export function UpdateSalaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSalaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'numero': json['numero'] == null ? undefined : json['numero'],
        'capacidade': json['capacidade'] == null ? undefined : json['capacidade'],
        'poutronas': json['poutronas'] == null ? undefined : ((json['poutronas'] as Array<any>).map(CreateSalaDtoPoutronasInnerFromJSON)),
        'cinemaId': json['cinemaId'] == null ? undefined : json['cinemaId'],
    };
}

export function UpdateSalaDtoToJSON(json: any): UpdateSalaDto {
    return UpdateSalaDtoToJSONTyped(json, false);
}

export function UpdateSalaDtoToJSONTyped(value?: UpdateSalaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numero': value['numero'],
        'capacidade': value['capacidade'],
        'poutronas': value['poutronas'] == null ? undefined : ((value['poutronas'] as Array<any>).map(CreateSalaDtoPoutronasInnerToJSON)),
        'cinemaId': value['cinemaId'],
    };
}

