/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateIngressoDto
 */
export interface UpdateIngressoDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateIngressoDto
     */
    valorInteira?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateIngressoDto
     */
    valorMeia?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateIngressoDto
     */
    sessaoId?: number;
}

/**
 * Check if a given object implements the UpdateIngressoDto interface.
 */
export function instanceOfUpdateIngressoDto(value: object): value is UpdateIngressoDto {
    return true;
}

export function UpdateIngressoDtoFromJSON(json: any): UpdateIngressoDto {
    return UpdateIngressoDtoFromJSONTyped(json, false);
}

export function UpdateIngressoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIngressoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'valorInteira': json['valorInteira'] == null ? undefined : json['valorInteira'],
        'valorMeia': json['valorMeia'] == null ? undefined : json['valorMeia'],
        'sessaoId': json['sessaoId'] == null ? undefined : json['sessaoId'],
    };
}

export function UpdateIngressoDtoToJSON(json: any): UpdateIngressoDto {
    return UpdateIngressoDtoToJSONTyped(json, false);
}

export function UpdateIngressoDtoToJSONTyped(value?: UpdateIngressoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valorInteira': value['valorInteira'],
        'valorMeia': value['valorMeia'],
        'sessaoId': value['sessaoId'],
    };
}

