/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSessaoDto
 */
export interface UpdateSessaoDto {
    /**
     * 
     * @type {Date}
     * @memberof UpdateSessaoDto
     */
    horarioExibicao?: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateSessaoDto
     */
    filmeId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSessaoDto
     */
    salaId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSessaoDto
     */
    cinemaId?: number;
}

/**
 * Check if a given object implements the UpdateSessaoDto interface.
 */
export function instanceOfUpdateSessaoDto(value: object): value is UpdateSessaoDto {
    return true;
}

export function UpdateSessaoDtoFromJSON(json: any): UpdateSessaoDto {
    return UpdateSessaoDtoFromJSONTyped(json, false);
}

export function UpdateSessaoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSessaoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'horarioExibicao': json['horarioExibicao'] == null ? undefined : (new Date(json['horarioExibicao'])),
        'filmeId': json['filmeId'] == null ? undefined : json['filmeId'],
        'salaId': json['salaId'] == null ? undefined : json['salaId'],
        'cinemaId': json['cinemaId'] == null ? undefined : json['cinemaId'],
    };
}

export function UpdateSessaoDtoToJSON(json: any): UpdateSessaoDto {
    return UpdateSessaoDtoToJSONTyped(json, false);
}

export function UpdateSessaoDtoToJSONTyped(value?: UpdateSessaoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'horarioExibicao': value['horarioExibicao'] == null ? undefined : ((value['horarioExibicao']).toISOString()),
        'filmeId': value['filmeId'],
        'salaId': value['salaId'],
        'cinemaId': value['cinemaId'],
    };
}

