/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLancheComboDto
 */
export interface UpdateLancheComboDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateLancheComboDto
     */
    nome?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLancheComboDto
     */
    descricao?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateLancheComboDto
     */
    valorUnitario?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateLancheComboDto
     */
    qtUnidade?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateLancheComboDto
     */
    subtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateLancheComboDto
     */
    pedidoId?: number;
}

/**
 * Check if a given object implements the UpdateLancheComboDto interface.
 */
export function instanceOfUpdateLancheComboDto(value: object): value is UpdateLancheComboDto {
    return true;
}

export function UpdateLancheComboDtoFromJSON(json: any): UpdateLancheComboDto {
    return UpdateLancheComboDtoFromJSONTyped(json, false);
}

export function UpdateLancheComboDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLancheComboDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nome': json['nome'] == null ? undefined : json['nome'],
        'descricao': json['descricao'] == null ? undefined : json['descricao'],
        'valorUnitario': json['valorUnitario'] == null ? undefined : json['valorUnitario'],
        'qtUnidade': json['qtUnidade'] == null ? undefined : json['qtUnidade'],
        'subtotal': json['subtotal'] == null ? undefined : json['subtotal'],
        'pedidoId': json['pedidoId'] == null ? undefined : json['pedidoId'],
    };
}

export function UpdateLancheComboDtoToJSON(json: any): UpdateLancheComboDto {
    return UpdateLancheComboDtoToJSONTyped(json, false);
}

export function UpdateLancheComboDtoToJSONTyped(value?: UpdateLancheComboDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nome': value['nome'],
        'descricao': value['descricao'],
        'valorUnitario': value['valorUnitario'],
        'qtUnidade': value['qtUnidade'],
        'subtotal': value['subtotal'],
        'pedidoId': value['pedidoId'],
    };
}

