/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFilmeDto
 */
export interface UpdateFilmeDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateFilmeDto
     */
    titulo?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFilmeDto
     */
    sinopse?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFilmeDto
     */
    classificacao?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateFilmeDto
     */
    duracao?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateFilmeDto
     */
    elenco?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFilmeDto
     */
    genero?: UpdateFilmeDtoGeneroEnum;
    /**
     * 
     * @type {Date}
     * @memberof UpdateFilmeDto
     */
    dataIniciaExibicao?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateFilmeDto
     */
    dataFinalExibicao?: Date;
}


/**
 * @export
 */
export const UpdateFilmeDtoGeneroEnum = {
    Acao: 'ACAO',
    Aventura: 'AVENTURA',
    Comedia: 'COMEDIA',
    Drama: 'DRAMA',
    Fantasia: 'FANTASIA',
    FiccaoCientifica: 'FICCAO_CIENTIFICA',
    Terror: 'TERROR',
    Romance: 'ROMANCE',
    Animacao: 'ANIMACAO',
    Documentario: 'DOCUMENTARIO',
    Suspense: 'SUSPENSE',
    Musical: 'MUSICAL',
    Outro: 'OUTRO'
} as const;
export type UpdateFilmeDtoGeneroEnum = typeof UpdateFilmeDtoGeneroEnum[keyof typeof UpdateFilmeDtoGeneroEnum];


/**
 * Check if a given object implements the UpdateFilmeDto interface.
 */
export function instanceOfUpdateFilmeDto(value: object): value is UpdateFilmeDto {
    return true;
}

export function UpdateFilmeDtoFromJSON(json: any): UpdateFilmeDto {
    return UpdateFilmeDtoFromJSONTyped(json, false);
}

export function UpdateFilmeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFilmeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'titulo': json['titulo'] == null ? undefined : json['titulo'],
        'sinopse': json['sinopse'] == null ? undefined : json['sinopse'],
        'classificacao': json['classificacao'] == null ? undefined : json['classificacao'],
        'duracao': json['duracao'] == null ? undefined : json['duracao'],
        'elenco': json['elenco'] == null ? undefined : json['elenco'],
        'genero': json['genero'] == null ? undefined : json['genero'],
        'dataIniciaExibicao': json['dataIniciaExibicao'] == null ? undefined : (new Date(json['dataIniciaExibicao'])),
        'dataFinalExibicao': json['dataFinalExibicao'] == null ? undefined : (new Date(json['dataFinalExibicao'])),
    };
}

export function UpdateFilmeDtoToJSON(json: any): UpdateFilmeDto {
    return UpdateFilmeDtoToJSONTyped(json, false);
}

export function UpdateFilmeDtoToJSONTyped(value?: UpdateFilmeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'titulo': value['titulo'],
        'sinopse': value['sinopse'],
        'classificacao': value['classificacao'],
        'duracao': value['duracao'],
        'elenco': value['elenco'],
        'genero': value['genero'],
        'dataIniciaExibicao': value['dataIniciaExibicao'] == null ? undefined : ((value['dataIniciaExibicao']).toISOString()),
        'dataFinalExibicao': value['dataFinalExibicao'] == null ? undefined : ((value['dataFinalExibicao']).toISOString()),
    };
}

