/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCinemaDto,
  UpdateCinemaDto,
} from '../models/index';
import {
    CreateCinemaDtoFromJSON,
    CreateCinemaDtoToJSON,
    UpdateCinemaDtoFromJSON,
    UpdateCinemaDtoToJSON,
} from '../models/index';

export interface CinemaControllerCadastrarFilmeRequest {
    cinemaId: number;
    filmeId: number;
}

export interface CinemaControllerCreateRequest {
    createCinemaDto: CreateCinemaDto;
}

export interface CinemaControllerFindOneRequest {
    id: number;
}

export interface CinemaControllerRemoveRequest {
    id: number;
}

export interface CinemaControllerRemoverFilmeRequest {
    cinemaId: number;
    filmeId: number;
}

export interface CinemaControllerUpdateRequest {
    id: number;
    updateCinemaDto: UpdateCinemaDto;
}

/**
 * 
 */
export class CinemaApi extends runtime.BaseAPI {

    /**
     * Associar filme ao cinema (M:N)
     */
    async cinemaControllerCadastrarFilmeRaw(requestParameters: CinemaControllerCadastrarFilmeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cinemaId'] == null) {
            throw new runtime.RequiredError(
                'cinemaId',
                'Required parameter "cinemaId" was null or undefined when calling cinemaControllerCadastrarFilme().'
            );
        }

        if (requestParameters['filmeId'] == null) {
            throw new runtime.RequiredError(
                'filmeId',
                'Required parameter "filmeId" was null or undefined when calling cinemaControllerCadastrarFilme().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cinema/{cinemaId}/filmes/{filmeId}`;
        urlPath = urlPath.replace(`{${"cinemaId"}}`, encodeURIComponent(String(requestParameters['cinemaId'])));
        urlPath = urlPath.replace(`{${"filmeId"}}`, encodeURIComponent(String(requestParameters['filmeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Associar filme ao cinema (M:N)
     */
    async cinemaControllerCadastrarFilme(requestParameters: CinemaControllerCadastrarFilmeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerCadastrarFilmeRaw(requestParameters, initOverrides);
    }

    /**
     * Criar novo cinema
     */
    async cinemaControllerCreateRaw(requestParameters: CinemaControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createCinemaDto'] == null) {
            throw new runtime.RequiredError(
                'createCinemaDto',
                'Required parameter "createCinemaDto" was null or undefined when calling cinemaControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cinema`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCinemaDtoToJSON(requestParameters['createCinemaDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar novo cinema
     */
    async cinemaControllerCreate(requestParameters: CinemaControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todos os cinemas
     */
    async cinemaControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cinema`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os cinemas
     */
    async cinemaControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar cinema por ID
     */
    async cinemaControllerFindOneRaw(requestParameters: CinemaControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cinemaControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cinema/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar cinema por ID
     */
    async cinemaControllerFindOne(requestParameters: CinemaControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover cinema
     */
    async cinemaControllerRemoveRaw(requestParameters: CinemaControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cinemaControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cinema/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover cinema
     */
    async cinemaControllerRemove(requestParameters: CinemaControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Desassociar filme do cinema
     */
    async cinemaControllerRemoverFilmeRaw(requestParameters: CinemaControllerRemoverFilmeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['cinemaId'] == null) {
            throw new runtime.RequiredError(
                'cinemaId',
                'Required parameter "cinemaId" was null or undefined when calling cinemaControllerRemoverFilme().'
            );
        }

        if (requestParameters['filmeId'] == null) {
            throw new runtime.RequiredError(
                'filmeId',
                'Required parameter "filmeId" was null or undefined when calling cinemaControllerRemoverFilme().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cinema/{cinemaId}/filmes/{filmeId}`;
        urlPath = urlPath.replace(`{${"cinemaId"}}`, encodeURIComponent(String(requestParameters['cinemaId'])));
        urlPath = urlPath.replace(`{${"filmeId"}}`, encodeURIComponent(String(requestParameters['filmeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Desassociar filme do cinema
     */
    async cinemaControllerRemoverFilme(requestParameters: CinemaControllerRemoverFilmeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerRemoverFilmeRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar cinema
     */
    async cinemaControllerUpdateRaw(requestParameters: CinemaControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cinemaControllerUpdate().'
            );
        }

        if (requestParameters['updateCinemaDto'] == null) {
            throw new runtime.RequiredError(
                'updateCinemaDto',
                'Required parameter "updateCinemaDto" was null or undefined when calling cinemaControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cinema/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCinemaDtoToJSON(requestParameters['updateCinemaDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar cinema
     */
    async cinemaControllerUpdate(requestParameters: CinemaControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cinemaControllerUpdateRaw(requestParameters, initOverrides);
    }

}
