/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateFilmeDto,
  UpdateFilmeDto,
} from '../models/index';
import {
    CreateFilmeDtoFromJSON,
    CreateFilmeDtoToJSON,
    UpdateFilmeDtoFromJSON,
    UpdateFilmeDtoToJSON,
} from '../models/index';

export interface FilmeControllerCreateRequest {
    createFilmeDto: CreateFilmeDto;
}

export interface FilmeControllerFindOneRequest {
    id: number;
}

export interface FilmeControllerRemoveRequest {
    id: number;
}

export interface FilmeControllerUpdateRequest {
    id: number;
    updateFilmeDto: UpdateFilmeDto;
}

/**
 * 
 */
export class FilmeApi extends runtime.BaseAPI {

    /**
     * Criar novo filme
     */
    async filmeControllerCreateRaw(requestParameters: FilmeControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createFilmeDto'] == null) {
            throw new runtime.RequiredError(
                'createFilmeDto',
                'Required parameter "createFilmeDto" was null or undefined when calling filmeControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/filme`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFilmeDtoToJSON(requestParameters['createFilmeDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar novo filme
     */
    async filmeControllerCreate(requestParameters: FilmeControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.filmeControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todos os filmes
     */
    async filmeControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/filme`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os filmes
     */
    async filmeControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.filmeControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar filme por ID
     */
    async filmeControllerFindOneRaw(requestParameters: FilmeControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling filmeControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/filme/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar filme por ID
     */
    async filmeControllerFindOne(requestParameters: FilmeControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.filmeControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover filme
     */
    async filmeControllerRemoveRaw(requestParameters: FilmeControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling filmeControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/filme/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover filme
     */
    async filmeControllerRemove(requestParameters: FilmeControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.filmeControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar filme
     */
    async filmeControllerUpdateRaw(requestParameters: FilmeControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling filmeControllerUpdate().'
            );
        }

        if (requestParameters['updateFilmeDto'] == null) {
            throw new runtime.RequiredError(
                'updateFilmeDto',
                'Required parameter "updateFilmeDto" was null or undefined when calling filmeControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/filme/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFilmeDtoToJSON(requestParameters['updateFilmeDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar filme
     */
    async filmeControllerUpdate(requestParameters: FilmeControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.filmeControllerUpdateRaw(requestParameters, initOverrides);
    }

}
