/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateIngressoDto,
  UpdateIngressoDto,
} from '../models/index';
import {
    CreateIngressoDtoFromJSON,
    CreateIngressoDtoToJSON,
    UpdateIngressoDtoFromJSON,
    UpdateIngressoDtoToJSON,
} from '../models/index';

export interface IngressoControllerCreateRequest {
    createIngressoDto: CreateIngressoDto;
}

export interface IngressoControllerFindOneRequest {
    id: number;
}

export interface IngressoControllerRemoveRequest {
    id: number;
}

export interface IngressoControllerUpdateRequest {
    id: number;
    updateIngressoDto: UpdateIngressoDto;
}

/**
 * 
 */
export class IngressoApi extends runtime.BaseAPI {

    /**
     * Criar novo ingresso
     */
    async ingressoControllerCreateRaw(requestParameters: IngressoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createIngressoDto'] == null) {
            throw new runtime.RequiredError(
                'createIngressoDto',
                'Required parameter "createIngressoDto" was null or undefined when calling ingressoControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ingresso`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateIngressoDtoToJSON(requestParameters['createIngressoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar novo ingresso
     */
    async ingressoControllerCreate(requestParameters: IngressoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingressoControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todos os ingressos
     */
    async ingressoControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ingresso`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os ingressos
     */
    async ingressoControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingressoControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar ingresso por ID
     */
    async ingressoControllerFindOneRaw(requestParameters: IngressoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ingressoControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ingresso/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar ingresso por ID
     */
    async ingressoControllerFindOne(requestParameters: IngressoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingressoControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover ingresso
     */
    async ingressoControllerRemoveRaw(requestParameters: IngressoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ingressoControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ingresso/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover ingresso
     */
    async ingressoControllerRemove(requestParameters: IngressoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingressoControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar ingresso
     */
    async ingressoControllerUpdateRaw(requestParameters: IngressoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ingressoControllerUpdate().'
            );
        }

        if (requestParameters['updateIngressoDto'] == null) {
            throw new runtime.RequiredError(
                'updateIngressoDto',
                'Required parameter "updateIngressoDto" was null or undefined when calling ingressoControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ingresso/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateIngressoDtoToJSON(requestParameters['updateIngressoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar ingresso
     */
    async ingressoControllerUpdate(requestParameters: IngressoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingressoControllerUpdateRaw(requestParameters, initOverrides);
    }

}
