/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLancheComboDto,
  UpdateLancheComboDto,
} from '../models/index';
import {
    CreateLancheComboDtoFromJSON,
    CreateLancheComboDtoToJSON,
    UpdateLancheComboDtoFromJSON,
    UpdateLancheComboDtoToJSON,
} from '../models/index';

export interface LancheComboControllerCreateRequest {
    createLancheComboDto: CreateLancheComboDto;
}

export interface LancheComboControllerFindOneRequest {
    id: number;
}

export interface LancheComboControllerRemoveRequest {
    id: number;
}

export interface LancheComboControllerUpdateRequest {
    id: number;
    updateLancheComboDto: UpdateLancheComboDto;
}

/**
 * 
 */
export class LancheComboApi extends runtime.BaseAPI {

    /**
     * Criar novo lanche/combo
     */
    async lancheComboControllerCreateRaw(requestParameters: LancheComboControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createLancheComboDto'] == null) {
            throw new runtime.RequiredError(
                'createLancheComboDto',
                'Required parameter "createLancheComboDto" was null or undefined when calling lancheComboControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/lanche-combo`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLancheComboDtoToJSON(requestParameters['createLancheComboDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar novo lanche/combo
     */
    async lancheComboControllerCreate(requestParameters: LancheComboControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lancheComboControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todos os lanches/combos
     */
    async lancheComboControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lanche-combo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os lanches/combos
     */
    async lancheComboControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lancheComboControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar lanche/combo por ID
     */
    async lancheComboControllerFindOneRaw(requestParameters: LancheComboControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lancheComboControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lanche-combo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar lanche/combo por ID
     */
    async lancheComboControllerFindOne(requestParameters: LancheComboControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lancheComboControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover lanche/combo
     */
    async lancheComboControllerRemoveRaw(requestParameters: LancheComboControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lancheComboControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/lanche-combo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover lanche/combo
     */
    async lancheComboControllerRemove(requestParameters: LancheComboControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lancheComboControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar lanche/combo
     */
    async lancheComboControllerUpdateRaw(requestParameters: LancheComboControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lancheComboControllerUpdate().'
            );
        }

        if (requestParameters['updateLancheComboDto'] == null) {
            throw new runtime.RequiredError(
                'updateLancheComboDto',
                'Required parameter "updateLancheComboDto" was null or undefined when calling lancheComboControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/lanche-combo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLancheComboDtoToJSON(requestParameters['updateLancheComboDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar lanche/combo
     */
    async lancheComboControllerUpdate(requestParameters: LancheComboControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.lancheComboControllerUpdateRaw(requestParameters, initOverrides);
    }

}
