/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePedidoDto,
  UpdatePedidoDto,
} from '../models/index';
import {
    CreatePedidoDtoFromJSON,
    CreatePedidoDtoToJSON,
    UpdatePedidoDtoFromJSON,
    UpdatePedidoDtoToJSON,
} from '../models/index';

export interface PedidoControllerAdicionaLancheRequest {
    pedidoId: number;
    lancheId: number;
}

export interface PedidoControllerAdicionarIngressoRequest {
    pedidoId: number;
    ingressoId: number;
}

export interface PedidoControllerCreateRequest {
    createPedidoDto: CreatePedidoDto;
}

export interface PedidoControllerFindOneRequest {
    id: number;
}

export interface PedidoControllerRemoveRequest {
    id: number;
}

export interface PedidoControllerRemoverIngressoRequest {
    pedidoId: number;
    ingressoId: number;
}

export interface PedidoControllerRemoverLancheRequest {
    pedidoId: number;
    lancheId: number;
}

export interface PedidoControllerUpdateRequest {
    id: number;
    updatePedidoDto: UpdatePedidoDto;
}

/**
 * 
 */
export class PedidoApi extends runtime.BaseAPI {

    /**
     * Adicionar lanche ao pedido
     */
    async pedidoControllerAdicionaLancheRaw(requestParameters: PedidoControllerAdicionaLancheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pedidoId'] == null) {
            throw new runtime.RequiredError(
                'pedidoId',
                'Required parameter "pedidoId" was null or undefined when calling pedidoControllerAdicionaLanche().'
            );
        }

        if (requestParameters['lancheId'] == null) {
            throw new runtime.RequiredError(
                'lancheId',
                'Required parameter "lancheId" was null or undefined when calling pedidoControllerAdicionaLanche().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{pedidoId}/lanches/{lancheId}`;
        urlPath = urlPath.replace(`{${"pedidoId"}}`, encodeURIComponent(String(requestParameters['pedidoId'])));
        urlPath = urlPath.replace(`{${"lancheId"}}`, encodeURIComponent(String(requestParameters['lancheId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adicionar lanche ao pedido
     */
    async pedidoControllerAdicionaLanche(requestParameters: PedidoControllerAdicionaLancheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerAdicionaLancheRaw(requestParameters, initOverrides);
    }

    /**
     * Adicionar ingresso ao pedido
     */
    async pedidoControllerAdicionarIngressoRaw(requestParameters: PedidoControllerAdicionarIngressoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pedidoId'] == null) {
            throw new runtime.RequiredError(
                'pedidoId',
                'Required parameter "pedidoId" was null or undefined when calling pedidoControllerAdicionarIngresso().'
            );
        }

        if (requestParameters['ingressoId'] == null) {
            throw new runtime.RequiredError(
                'ingressoId',
                'Required parameter "ingressoId" was null or undefined when calling pedidoControllerAdicionarIngresso().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{pedidoId}/ingressos/{ingressoId}`;
        urlPath = urlPath.replace(`{${"pedidoId"}}`, encodeURIComponent(String(requestParameters['pedidoId'])));
        urlPath = urlPath.replace(`{${"ingressoId"}}`, encodeURIComponent(String(requestParameters['ingressoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adicionar ingresso ao pedido
     */
    async pedidoControllerAdicionarIngresso(requestParameters: PedidoControllerAdicionarIngressoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerAdicionarIngressoRaw(requestParameters, initOverrides);
    }

    /**
     * Criar novo pedido
     */
    async pedidoControllerCreateRaw(requestParameters: PedidoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createPedidoDto'] == null) {
            throw new runtime.RequiredError(
                'createPedidoDto',
                'Required parameter "createPedidoDto" was null or undefined when calling pedidoControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pedido`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePedidoDtoToJSON(requestParameters['createPedidoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar novo pedido
     */
    async pedidoControllerCreate(requestParameters: PedidoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todos os pedidos
     */
    async pedidoControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todos os pedidos
     */
    async pedidoControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar pedido por ID
     */
    async pedidoControllerFindOneRaw(requestParameters: PedidoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pedidoControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar pedido por ID
     */
    async pedidoControllerFindOne(requestParameters: PedidoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover pedido
     */
    async pedidoControllerRemoveRaw(requestParameters: PedidoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pedidoControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover pedido
     */
    async pedidoControllerRemove(requestParameters: PedidoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Remover ingresso do pedido
     */
    async pedidoControllerRemoverIngressoRaw(requestParameters: PedidoControllerRemoverIngressoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pedidoId'] == null) {
            throw new runtime.RequiredError(
                'pedidoId',
                'Required parameter "pedidoId" was null or undefined when calling pedidoControllerRemoverIngresso().'
            );
        }

        if (requestParameters['ingressoId'] == null) {
            throw new runtime.RequiredError(
                'ingressoId',
                'Required parameter "ingressoId" was null or undefined when calling pedidoControllerRemoverIngresso().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{pedidoId}/ingressos/{ingressoId}`;
        urlPath = urlPath.replace(`{${"pedidoId"}}`, encodeURIComponent(String(requestParameters['pedidoId'])));
        urlPath = urlPath.replace(`{${"ingressoId"}}`, encodeURIComponent(String(requestParameters['ingressoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover ingresso do pedido
     */
    async pedidoControllerRemoverIngresso(requestParameters: PedidoControllerRemoverIngressoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerRemoverIngressoRaw(requestParameters, initOverrides);
    }

    /**
     * Remover lanche do pedido
     */
    async pedidoControllerRemoverLancheRaw(requestParameters: PedidoControllerRemoverLancheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pedidoId'] == null) {
            throw new runtime.RequiredError(
                'pedidoId',
                'Required parameter "pedidoId" was null or undefined when calling pedidoControllerRemoverLanche().'
            );
        }

        if (requestParameters['lancheId'] == null) {
            throw new runtime.RequiredError(
                'lancheId',
                'Required parameter "lancheId" was null or undefined when calling pedidoControllerRemoverLanche().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pedido/{pedidoId}/lanches/{lancheId}`;
        urlPath = urlPath.replace(`{${"pedidoId"}}`, encodeURIComponent(String(requestParameters['pedidoId'])));
        urlPath = urlPath.replace(`{${"lancheId"}}`, encodeURIComponent(String(requestParameters['lancheId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover lanche do pedido
     */
    async pedidoControllerRemoverLanche(requestParameters: PedidoControllerRemoverLancheRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerRemoverLancheRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar pedido
     */
    async pedidoControllerUpdateRaw(requestParameters: PedidoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling pedidoControllerUpdate().'
            );
        }

        if (requestParameters['updatePedidoDto'] == null) {
            throw new runtime.RequiredError(
                'updatePedidoDto',
                'Required parameter "updatePedidoDto" was null or undefined when calling pedidoControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pedido/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePedidoDtoToJSON(requestParameters['updatePedidoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar pedido
     */
    async pedidoControllerUpdate(requestParameters: PedidoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pedidoControllerUpdateRaw(requestParameters, initOverrides);
    }

}
