/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSalaDto,
  SalaControllerReservarPoutronaRequest,
  UpdateSalaDto,
} from '../models/index';
import {
    CreateSalaDtoFromJSON,
    CreateSalaDtoToJSON,
    SalaControllerReservarPoutronaRequestFromJSON,
    SalaControllerReservarPoutronaRequestToJSON,
    UpdateSalaDtoFromJSON,
    UpdateSalaDtoToJSON,
} from '../models/index';

export interface SalaControllerCalcularCapacidadeRequest {
    id: number;
}

export interface SalaControllerCreateRequest {
    createSalaDto: CreateSalaDto;
}

export interface SalaControllerFindOneRequest {
    id: number;
}

export interface SalaControllerRemoveRequest {
    id: number;
}

export interface SalaControllerReservarPoutronaOperationRequest {
    id: number;
    salaControllerReservarPoutronaRequest: SalaControllerReservarPoutronaRequest;
}

export interface SalaControllerUpdateRequest {
    id: number;
    updateSalaDto: UpdateSalaDto;
}

/**
 * 
 */
export class SalaApi extends runtime.BaseAPI {

    /**
     * Calcular capacidade disponível da sala
     */
    async salaControllerCalcularCapacidadeRaw(requestParameters: SalaControllerCalcularCapacidadeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling salaControllerCalcularCapacidade().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sala/{id}/capacidade`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Calcular capacidade disponível da sala
     */
    async salaControllerCalcularCapacidade(requestParameters: SalaControllerCalcularCapacidadeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerCalcularCapacidadeRaw(requestParameters, initOverrides);
    }

    /**
     * Criar nova sala
     */
    async salaControllerCreateRaw(requestParameters: SalaControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createSalaDto'] == null) {
            throw new runtime.RequiredError(
                'createSalaDto',
                'Required parameter "createSalaDto" was null or undefined when calling salaControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sala`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSalaDtoToJSON(requestParameters['createSalaDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar nova sala
     */
    async salaControllerCreate(requestParameters: SalaControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todas as salas
     */
    async salaControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sala`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todas as salas
     */
    async salaControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar sala por ID
     */
    async salaControllerFindOneRaw(requestParameters: SalaControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling salaControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sala/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar sala por ID
     */
    async salaControllerFindOne(requestParameters: SalaControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover sala
     */
    async salaControllerRemoveRaw(requestParameters: SalaControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling salaControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sala/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover sala
     */
    async salaControllerRemove(requestParameters: SalaControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Reservar uma poltrona
     */
    async salaControllerReservarPoutronaRaw(requestParameters: SalaControllerReservarPoutronaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling salaControllerReservarPoutrona().'
            );
        }

        if (requestParameters['salaControllerReservarPoutronaRequest'] == null) {
            throw new runtime.RequiredError(
                'salaControllerReservarPoutronaRequest',
                'Required parameter "salaControllerReservarPoutronaRequest" was null or undefined when calling salaControllerReservarPoutrona().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sala/{id}/reservar`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalaControllerReservarPoutronaRequestToJSON(requestParameters['salaControllerReservarPoutronaRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reservar uma poltrona
     */
    async salaControllerReservarPoutrona(requestParameters: SalaControllerReservarPoutronaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerReservarPoutronaRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar sala
     */
    async salaControllerUpdateRaw(requestParameters: SalaControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling salaControllerUpdate().'
            );
        }

        if (requestParameters['updateSalaDto'] == null) {
            throw new runtime.RequiredError(
                'updateSalaDto',
                'Required parameter "updateSalaDto" was null or undefined when calling salaControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sala/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSalaDtoToJSON(requestParameters['updateSalaDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar sala
     */
    async salaControllerUpdate(requestParameters: SalaControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.salaControllerUpdateRaw(requestParameters, initOverrides);
    }

}
