/* tslint:disable */
/* eslint-disable */
/**
 * Cinema Management API
 * REST API para gerenciamento de cinema: cinemas, salas, filmes, sessões, ingressos e pedidos
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSessaoDto,
  UpdateSessaoDto,
} from '../models/index';
import {
    CreateSessaoDtoFromJSON,
    CreateSessaoDtoToJSON,
    UpdateSessaoDtoFromJSON,
    UpdateSessaoDtoToJSON,
} from '../models/index';

export interface SessaoControllerCreateRequest {
    createSessaoDto: CreateSessaoDto;
}

export interface SessaoControllerFindOneRequest {
    id: number;
}

export interface SessaoControllerRemoveRequest {
    id: number;
}

export interface SessaoControllerUpdateRequest {
    id: number;
    updateSessaoDto: UpdateSessaoDto;
}

/**
 * 
 */
export class SessaoApi extends runtime.BaseAPI {

    /**
     * Criar nova sessão
     */
    async sessaoControllerCreateRaw(requestParameters: SessaoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createSessaoDto'] == null) {
            throw new runtime.RequiredError(
                'createSessaoDto',
                'Required parameter "createSessaoDto" was null or undefined when calling sessaoControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sessao`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessaoDtoToJSON(requestParameters['createSessaoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Criar nova sessão
     */
    async sessaoControllerCreate(requestParameters: SessaoControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessaoControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Listar todas as sessões
     */
    async sessaoControllerFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sessao`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Listar todas as sessões
     */
    async sessaoControllerFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessaoControllerFindAllRaw(initOverrides);
    }

    /**
     * Buscar sessão por ID
     */
    async sessaoControllerFindOneRaw(requestParameters: SessaoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessaoControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sessao/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Buscar sessão por ID
     */
    async sessaoControllerFindOne(requestParameters: SessaoControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessaoControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Remover sessão
     */
    async sessaoControllerRemoveRaw(requestParameters: SessaoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessaoControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sessao/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remover sessão
     */
    async sessaoControllerRemove(requestParameters: SessaoControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessaoControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Atualizar sessão
     */
    async sessaoControllerUpdateRaw(requestParameters: SessaoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sessaoControllerUpdate().'
            );
        }

        if (requestParameters['updateSessaoDto'] == null) {
            throw new runtime.RequiredError(
                'updateSessaoDto',
                'Required parameter "updateSessaoDto" was null or undefined when calling sessaoControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sessao/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSessaoDtoToJSON(requestParameters['updateSessaoDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Atualizar sessão
     */
    async sessaoControllerUpdate(requestParameters: SessaoControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sessaoControllerUpdateRaw(requestParameters, initOverrides);
    }

}
